name: auto_update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Instalar librerias
        run: pip install requests
        
      - name: Ejecutar Actualizacion
        run: |
          python update_data.py || (echo "EL SCRIPT FALLO" && exit 1)
          
      - name: Guardar Cambios en GitHub
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html
          git commit -m "Update automatico" || exit 0
          git push
